const db = require("./config/db");

db.serialize(() => {

  db.run(`
    INSERT OR IGNORE INTO village_links
    (district, tehsil, village)
    VALUES
    ('Charkhi Dadri','Badhra','BADHRA'),
('Charkhi Dadri','Badhra','BADRAI'),
('Charkhi Dadri','Badhra','BERLA'),
('Charkhi Dadri','Badhra','BHANDWA'),
('Charkhi Dadri','Badhra','BHARIWAS'),
('Charkhi Dadri','Badhra','BHOPALI'),
('Charkhi Dadri','Badhra','BILAWAL'),
('Charkhi Dadri','Badhra','BINDRABAN'),
('Charkhi Dadri','Badhra','CHANDWAS'),
('Charkhi Dadri','Badhra','DAGROLI'),
('Charkhi Dadri','Badhra','DALAWAS'),
('Charkhi Dadri','Badhra','DANDMA'),
('Charkhi Dadri','Badhra','DHANASRI'),
('Charkhi Dadri','Badhra','DWARKA'),
('Charkhi Dadri','Badhra','GOPALWAS'),
('Charkhi Dadri','Badhra','GOPI'),
('Charkhi Dadri','Badhra','GOVINDPURA'),
('Charkhi Dadri','Badhra','HANSAWAS KALAN'),
('Charkhi Dadri','Badhra','HANSAWAS KHURD'),
('Charkhi Dadri','Badhra','HUI'),
('Charkhi Dadri','Badhra','JAGRAMBASS'),
('Charkhi Dadri','Badhra','JEETPURA'),
('Charkhi Dadri','Badhra','JEWALI'),
('Charkhi Dadri','Badhra','KADMA'),
('Charkhi Dadri','Badhra','KAKROLI HATTI'),
('Charkhi Dadri','Badhra','KAKROLI HUKMI'),
('Charkhi Dadri','Badhra','KAKROLI SARDARA'),
('Charkhi Dadri','Badhra','KANHRA'),
('Charkhi Dadri','Badhra','KARI ADU'),
('Charkhi Dadri','Badhra','KARI DASS'),
('Charkhi Dadri','Badhra','KARI DHARNI'),
('Charkhi Dadri','Badhra','KARI MOD'),
('Charkhi Dadri','Badhra','KARI RUPA'),
('Charkhi Dadri','Badhra','KARI TOKHA'),
('Charkhi Dadri','Badhra','KHORDA'),
('Charkhi Dadri','Badhra','KISHKANDHA'),
('Charkhi Dadri','Badhra','KUBJA NAGAR'),
('Charkhi Dadri','Badhra','LAD'),
('Charkhi Dadri','Badhra','LADAWAS'),
('Charkhi Dadri','Badhra','MANDI HARIYA'),
('Charkhi Dadri','Badhra','MANDI KEHAR'),
('Charkhi Dadri','Badhra','MANDI PIRANU'),
('Charkhi Dadri','Badhra','MUTHRA'),
('Charkhi Dadri','Badhra','NANDHA'),
('Charkhi Dadri','Badhra','NIMAR'),
('Charkhi Dadri','Badhra','PANCHGAON'),
('Charkhi Dadri','Badhra','PICHOPA KHURD'),
('Charkhi Dadri','Badhra','REHRODA KALAN'),
('Charkhi Dadri','Badhra','REHRODA KHURD'),
('Charkhi Dadri','Badhra','REHRODI'),
('Charkhi Dadri','Badhra','SHYAM KALAN'),
('Charkhi Dadri','Badhra','SURAJGARH'),
('Charkhi Dadri','Badhra','TODI'),
('Charkhi Dadri','Badhra','UMARWAS'),
('Charkhi Dadri','Charkhi Dadri','ABIDPURA'),
('Charkhi Dadri','Charkhi Dadri','AKHTYARPURA'),
('Charkhi Dadri','Charkhi Dadri','ASAWRI'),
('Charkhi Dadri','Charkhi Dadri','ATELA KALAN'),
('Charkhi Dadri','Charkhi Dadri','ATELA KHURD'),
('Charkhi Dadri','Charkhi Dadri','BADAL'),
('Charkhi Dadri','Charkhi Dadri','BADHWANA'),
('Charkhi Dadri','Charkhi Dadri','BALALI'),
('Charkhi Dadri','Charkhi Dadri','BALKARA'),
('Charkhi Dadri','Charkhi Dadri','BALROD'),
('Charkhi Dadri','Charkhi Dadri','BARSANA'),
('Charkhi Dadri','Charkhi Dadri','BHAGVI'),
('Charkhi Dadri','Charkhi Dadri','BHERVI'),
('Charkhi Dadri','Charkhi Dadri','BIGOWA'),
('Charkhi Dadri','Charkhi Dadri','BIJNA'),
('Charkhi Dadri','Charkhi Dadri','BIRHI KALAN'),
('Charkhi Dadri','Charkhi Dadri','BIRHI KHURD'),
('Charkhi Dadri','Charkhi Dadri','BIRSAMASPUR'),
('Charkhi Dadri','Charkhi Dadri','CHANDENI'),
('Charkhi Dadri','Charkhi Dadri','CHANGROD'),
('Charkhi Dadri','Charkhi Dadri','CHARKHI'),
('Charkhi Dadri','Charkhi Dadri','CHHAPAR'),
('Charkhi Dadri','Charkhi Dadri','CHIRIYA'),
('Charkhi Dadri','Charkhi Dadri','DADHI BANA'),
('Charkhi Dadri','Charkhi Dadri','DADHI CHHILAR'),
('Charkhi Dadri','Charkhi Dadri','DADRI'),
('Charkhi Dadri','Charkhi Dadri','DATOLI'),
('Charkhi Dadri','Charkhi Dadri','DHANI PHOGAT'),
('Charkhi Dadri','Charkhi Dadri','DOHKA DINA'),
('Charkhi Dadri','Charkhi Dadri','DOHKA HARYA'),
('Charkhi Dadri','Charkhi Dadri','DOHKA MOJI'),
('Charkhi Dadri','Charkhi Dadri','DOHKI'),
('Charkhi Dadri','Charkhi Dadri','DUDHWA'),
('Charkhi Dadri','Charkhi Dadri','DUDIWALA KISHANPURA'),
('Charkhi Dadri','Charkhi Dadri','DUDIWALA NANDKARAN'),
('Charkhi Dadri','Charkhi Dadri','FATEHGARH'),
('Charkhi Dadri','Charkhi Dadri','GHASOLA'),
('Charkhi Dadri','Charkhi Dadri','GHIKARA'),
('Charkhi Dadri','Charkhi Dadri','GOKAL'),
('Charkhi Dadri','Charkhi Dadri','GOTHRA'),
('Charkhi Dadri','Charkhi Dadri','GUDANA'),
('Charkhi Dadri','Charkhi Dadri','IMLOTA'),
('Charkhi Dadri','Charkhi Dadri','JAISHREE'),
('Charkhi Dadri','Charkhi Dadri','JAWA'),
('Charkhi Dadri','Charkhi Dadri','JHOJHU KALAN'),
('Charkhi Dadri','Charkhi Dadri','JHOJHU KHURD'),
('Charkhi Dadri','Charkhi Dadri','KALALI'),
('Charkhi Dadri','Charkhi Dadri','KALIYANA'),
('Charkhi Dadri','Charkhi Dadri','KAMOD'),
('Charkhi Dadri','Charkhi Dadri','KANHETI'),
('Charkhi Dadri','Charkhi Dadri','KHATIWAS'),
('Charkhi Dadri','Charkhi Dadri','KHERI BATTAR'),
('Charkhi Dadri','Charkhi Dadri','KHERI BURA'),
('Charkhi Dadri','Charkhi Dadri','KHERI SANWAL'),
('Charkhi Dadri','Charkhi Dadri','KIDARA'),
('Charkhi Dadri','Charkhi Dadri','LOHARWARA'),
('Charkhi Dadri','Charkhi Dadri','MAI KALAN'),
('Charkhi Dadri','Charkhi Dadri','MAI KHURD'),
('Charkhi Dadri','Charkhi Dadri','MAKRANA'),
('Charkhi Dadri','Charkhi Dadri','MAKRANI'),
('Charkhi Dadri','Charkhi Dadri','MANDOLA'),
('Charkhi Dadri','Charkhi Dadri','MANDOLI'),
('Charkhi Dadri','Charkhi Dadri','MANKAWAS'),
('Charkhi Dadri','Charkhi Dadri','MEHRA'),
('Charkhi Dadri','Charkhi Dadri','MEHRANA'),
('Charkhi Dadri','Charkhi Dadri','MISSRI'),
('Charkhi Dadri','Charkhi Dadri','MORI'),
('Charkhi Dadri','Charkhi Dadri','MORWALA'),
('Charkhi Dadri','Charkhi Dadri','NARSINGWAS'),
('Charkhi Dadri','Charkhi Dadri','NIMLI'),
('Charkhi Dadri','Charkhi Dadri','NORANGAWAS JATTAN'),
('Charkhi Dadri','Charkhi Dadri','NORANGAWAS RAJPUTAN'),
('Charkhi Dadri','Charkhi Dadri','NOSWA'),
('Charkhi Dadri','Charkhi Dadri','PAINTAWAS KALAN'),
('Charkhi Dadri','Charkhi Dadri','PAINTAWAS KHURD'),
('Charkhi Dadri','Charkhi Dadri','PALRI'),
('Charkhi Dadri','Charkhi Dadri','PANDWAN'),
('Charkhi Dadri','Charkhi Dadri','PATUWAS'),
('Charkhi Dadri','Charkhi Dadri','PICHOPA KALAN'),
('Charkhi Dadri','Charkhi Dadri','RAMALWAS'),
('Charkhi Dadri','Charkhi Dadri','RAMBASS'),
('Charkhi Dadri','Charkhi Dadri','RAMNAGAR KAPOORI'),
('Charkhi Dadri','Charkhi Dadri','RAMPURA'),
('Charkhi Dadri','Charkhi Dadri','RASIWAS'),
('Charkhi Dadri','Charkhi Dadri','RAWALDHI'),
('Charkhi Dadri','Charkhi Dadri','RUDROL'),
('Charkhi Dadri','Charkhi Dadri','SAHUWAS'),
('Charkhi Dadri','Charkhi Dadri','SAMASPUR'),
('Charkhi Dadri','Charkhi Dadri','SANTOKHPURA'),
('Charkhi Dadri','Charkhi Dadri','SANTOR'),
('Charkhi Dadri','Charkhi Dadri','SARANGPUR'),
('Charkhi Dadri','Charkhi Dadri','SARUPGARH'),
('Charkhi Dadri','Charkhi Dadri','SHISWALA'),
('Charkhi Dadri','Charkhi Dadri','TIKAN KALAN'),
('Charkhi Dadri','Charkhi Dadri','TIKAN KHURD'),
('Charkhi Dadri','Charkhi Dadri','TIWALA'),
('Charkhi Dadri','Charkhi Dadri','UNNEAR BADHWANA'),
('Charkhi Dadri','Bond Kalan','ACHINA'),
('Charkhi Dadri','Bond Kalan','BAS MUTSIL RANILA'),
('Charkhi Dadri','Bond Kalan','BHAGESHWARI'),
('Charkhi Dadri','Bond Kalan','BOND KALAN'),
('Charkhi Dadri','Bond Kalan','BOND KHURD'),
('Charkhi Dadri','Bond Kalan','HINDOL'),
('Charkhi Dadri','Bond Kalan','JHINJHAR'),
('Charkhi Dadri','Bond Kalan','KASNI'),
('Charkhi Dadri','Bond Kalan','KOHLAWAS'),
('Charkhi Dadri','Bond Kalan','LAMBA'),
('Charkhi Dadri','Bond Kalan','MALKOSH'),
('Charkhi Dadri','Bond Kalan','MIRCH'),
('Charkhi Dadri','Bond Kalan','NIMRI'),
('Charkhi Dadri','Bond Kalan','PHOGAT'),
('Charkhi Dadri','Bond Kalan','RANILA'),
('Charkhi Dadri','Bond Kalan','RANKOLI'),
('Charkhi Dadri','Bond Kalan','SANJHARWAS'),
('Charkhi Dadri','Bond Kalan','SANKROR'),
('Charkhi Dadri','Bond Kalan','SANWAR'),
('Charkhi Dadri','Bond Kalan','SONF'),
('Charkhi Dadri','Bond Kalan','UNE MUTSILBOND KALAN');
  `, (err) => {

    if (err) {
      console.log(err);
    } else {
      console.log("Done");
    }

    process.exit();
  });

});